baseurl = "https://www.drmoron.org"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "The Blog of Dr. Moron"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

# This is necessary to make shortcodes work with markdown and
# other html/markdown mix.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "I blog because there is no peer review like no peer review."
  mainSections = ["post","posts"]
  #logo = "img/avatar-icon.png" # Expecting square dimensions
  logo = "https://www.gravatar.com/avatar/5785d806cffc98ab63daa2d1a43f0c5e?s=100"
  favicon = "favicon.png"
  dateFormat = "January 2, 2006"
  since = 2013
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = false
  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Kenneth Moreland"
  website = "https://www.kennethmoreland.com"
  email = "morelandsnl@gmail.com"
  facebook = "kenneth.moreland.7"
  github = "kmorel"
  gitlab = "kmorel"
  bitbucket = "kennethmoreland"
  #twitter = "username"
  #reddit = "dr-moron"
  linkedin = "kmorel"
  #xing = "username"
  stackoverflow = "users/4971509/kenneth-moreland"
  #snapchat = "username"
  #instagram = "username"
  youtube = "channel/UC775K7V57u6GXF2jBqeUSMw" # or channel/channelname user/username
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  3telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  #discord = "invite code (https://discord.gg/XXXXXXX)"
  #strava = "userid"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

# [[menu.main]]
#     identifier = "samples"
#     name = "Samples"
#     weight = 2

# [[menu.main]]
#     parent = "samples"
#     name = "Big Image Sample"
#     url = "post/2017-03-07-bigimg-sample"
#     weight = 1

# [[menu.main]]
#     parent = "samples"
#     name = "Math Sample"
#     url = "post/2017-03-05-math-sample"
#     weight = 2

# [[menu.main]]
#     parent = "samples"
#     name = "Code Sample"
#     url = "post/2016-03-08-code-sample"
#     weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
